# Generated by Django 6.1 on 2026-09-01 03:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickingListBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipped_on', models.DateField()),
                ('sent_by', models.CharField(max_length=120)),
                ('customer_route', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PickingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('customer_route', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_process', 'In process'), ('invoiced', 'Invoiced'), ('error', 'Error'), ('corrected', 'Corrected')], default='not_started', max_length=20)),
                ('handed_off_at', models.DateTimeField()),
                ('in_process_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=40)),
                ('invoiced_at', models.DateTimeField(blank=True, null=True)),
                ('handled_by', models.ForeignKey(blank=True, help_text='The assistant who processed this list — counts toward their KPI.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picking_lists_handled', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='tracker.pickinglistbatch')),
            ],
            options={
                'ordering': ['-handed_off_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=40)),
                ('error_type', models.CharField(max_length=150)),
                ('attributable_to', models.CharField(choices=[('assistant', 'Assistant'), ('logistics', 'Logistics data'), ('customer', 'Customer master data')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('reported_by', models.CharField(blank=True, max_length=120)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('corrected_at', models.DateTimeField(blank=True, null=True)),
                ('disputed', models.BooleanField(default=False)),
                ('picking_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='tracker.pickinglist')),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('requester_name', models.CharField(max_length=120)),
                ('requester_email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=120)),
                ('needed_by', models.DateField()),
                ('justification', models.TextField(blank=True, verbose_name='Why is it needed?')),
                ('urgency', models.CharField(choices=[('standard', 'Standard — 5 working days'), ('priority', 'Priority — 48 hours'), ('line_stopped', 'Line stopped')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('quoting', 'Quotes requested'), ('quotes_in', 'Quotes in'), ('po_issued', 'PO issued'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('po_number', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quoting_started_at', models.DateTimeField(blank=True, null=True)),
                ('po_issued_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('handled_by', models.ForeignKey(blank=True, help_text='The assistant who issued the Purchase Order — counts toward their KPI.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests_handled', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tracker.purchaserequest')),
            ],
            options={
                'verbose_name_plural': 'purchase activities',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tracker.purchaserequest')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=150)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='MXN', max_length=8)),
                ('lead_time_days', models.PositiveIntegerField()),
                ('payment_terms', models.CharField(blank=True, max_length=80)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('selected', models.BooleanField(default=False)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='tracker.purchaserequest')),
            ],
            options={
                'ordering': ['received_at'],
            },
        ),
    ]
