# Generated by Django 6.1 on 2026-09-01 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseactivity',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'actividades de compra'},
        ),
        migrations.AlterField(
            model_name='billingerror',
            name='attributable_to',
            field=models.CharField(choices=[('assistant', 'Asistente'), ('logistics', 'Datos de logística'), ('customer', 'Datos maestros del cliente')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pickinglist',
            name='handled_by',
            field=models.ForeignKey(blank=True, help_text='La asistente que procesó esta lista — cuenta para su KPI.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picking_lists_handled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pickinglist',
            name='status',
            field=models.CharField(choices=[('not_started', 'Sin iniciar'), ('in_process', 'En proceso'), ('invoiced', 'Facturada'), ('error', 'Error'), ('corrected', 'Corregida')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='handled_by',
            field=models.ForeignKey(blank=True, help_text='La asistente que emitió la orden de compra — cuenta para su KPI.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests_handled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='justification',
            field=models.TextField(blank=True, verbose_name='¿Para qué se necesita?'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Solicitada'), ('quoting', 'Cotizaciones solicitadas'), ('quotes_in', 'Cotizaciones recibidas'), ('po_issued', 'Orden de compra emitida'), ('closed', 'Cerrada'), ('cancelled', 'Cancelada')], default='requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='urgency',
            field=models.CharField(choices=[('standard', 'Estándar — 5 días hábiles'), ('priority', 'Prioritaria — 48 horas'), ('line_stopped', 'Línea detenida')], default='standard', max_length=20),
        ),
    ]
