# Generated by Django 6.1 on 2026-09-02 18:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_purchaserequest_reference_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequestitem',
            name='reference_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Foto de referencia de este artículo (opcional).', max_length=255, null=True, verbose_name='imagen'),
        ),
    ]
