# Generated by Django 6.1 on 2026-09-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_purchaserequestitem_reference_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequestitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
