# Generated by Django 6.1 on 2026-09-02 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_purchaserequestitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickinglist',
            name='customer_route',
        ),
        migrations.RemoveField(
            model_name='pickinglistbatch',
            name='customer_route',
        ),
        migrations.RemoveField(
            model_name='pickinglistbatch',
            name='sent_by',
        ),
    ]
