# Generated by Django 6.1 on 2026-10-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_remove_purchaserequest_quoting_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='urgency',
            field=models.CharField(choices=[('standard', 'Estándar — 5 días hábiles'), ('priority', 'Prioritaria — 48 horas'), ('line_stopped', 'Línea detenida — 8 horas')], default='standard', max_length=20),
        ),
    ]
