# Generated by Django 6.1 on 2026-10-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_purchaserequest_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierquote',
            name='currency',
            field=models.CharField(blank=True, default='CLP', max_length=8),
        ),
    ]
