# Generated by Django 6.1 on 2026-10-06 18:54

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_supplierquote_currency_clp'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseactivity',
            name='author',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='purchaseactivity',
            name='kind',
            field=models.CharField(choices=[('event', 'Evento'), ('requester_message', 'Mensaje del solicitante'), ('staff_message', 'Mensaje de Compras')], default='event', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='po_pdf',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='PDF de la orden de compra emitida (opcional).', max_length=255, null=True, verbose_name='orden de compra'),
        ),
        migrations.AlterField(
            model_name='purchaseactivity',
            name='message',
            field=models.TextField(),
        ),
    ]
