# Generated by Django 6.1 on 2026-10-06 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_purchase_flow_self_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='reminded_at',
            field=models.DateTimeField(blank=True, help_text='Último recordatorio enviado al solicitante para elegir cotización.', null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='requester_wait_time',
            field=models.DurationField(default=datetime.timedelta, help_text='Tiempo acumulado esperando que el solicitante respondiera a las cotizaciones.'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='single_source_reason',
            field=models.TextField(blank=True, help_text='Por qué se enviaron menos cotizaciones que el mínimo (p. ej. proveedor único).'),
        ),
    ]
