# Generated by Django 6.1 on 2026-10-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0012_purchase_kpi_pause_and_followup"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingerror",
            name="corrected_invoice_number",
            field=models.CharField(
                blank=True,
                help_text="Factura emitida para corregir la original (opcional).",
                max_length=40,
            ),
        ),
    ]
